
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bm.java
 *
 * Created on Jul 8, 2011, 12:35:00 AM
 */

/**
 *
 * @author SHYFUL
 */
public class bm extends javax.swing.JPanel {

    /** Creates new form bm */
    public bm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 320, -1));

        jLabel2.setText("Age:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 320, -1));

        jLabel3.setText("Gender:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 320, -1));

        jLabel4.setText("Blood Group:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 320, -1));

        jLabel5.setText("Profession:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 320, -1));

        jLabel7.setText("Present Address:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 320, 50));

        jLabel8.setText("Permanent Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 320, 50));

        jLabel13.setText("Total Donation :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel18.setText("Phone No :");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel14.setText("Last Donation Date :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 320, -1));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 320, -1));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 320, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, 20));
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 60, -1));

        jLabel9.setText("Enter id:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 20));

        jButton2.setText("Upgrade");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 100, 20));

        jButton3.setText("Delete");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 100, 20));

        jButton4.setText("Donation");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Connection con = null;
        String url = "jdbc:mysql://localhost:3306/";
        String db = "bd";
        String driver = "com.mysql.jdbc.Driver";
        String user = "root";
        String pass = "";



        try {
            int x = JOptionPane.showConfirmDialog(null, "Are you sure to Confirm edit? All data will be replaced by present data !");
            if (x == 0) {
                try {

                    Class.forName(driver);
                    con = (Connection) DriverManager.getConnection(url + db, user, pass);
                    Statement st = (Statement) con.createStatement();
                    st.executeUpdate("UPDATE `bd`.`add` SET `idn` = '" + jTextField10.getText() + "', `Name` = '" + jTextField1.getText() + "', `agey` = '" + jTextField2.getText() + "', `gdr` = '" + jTextField3.getText() + "', `bg` = '" + jTextField4.getText() + "',  `profession` = '" + jTextField5.getText() + "',`pre` = '" + jTextArea1.getText() + "', `per` = '" + jTextArea2.getText() + "', `ttld` = '" + jTextField7.getText() + "', `pn` = '" + jTextField8.getText() + "', `Lddd` = '" + jTextField9.getText() + "' WHERE `idn` = '" + jTextField10.getText() + "' ");


                    JOptionPane.showMessageDialog(null, "Updated successfully completed");
                    con.close();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error in updating, please edit fields again !");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error");
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


                                  Connection con=null;
     PreparedStatement stm=null;
        try {
        Class.forName("com.mysql.jdbc.Driver");
        }catch (ClassNotFoundException ex) {
        Logger.getLogger(BM5.class.getName()).log(Level.SEVERE, null, ex);
        }
        int i=0;
        try {
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bd","root","");
            stm = (PreparedStatement) con.prepareStatement("select * from `add` where `idn`=?");
            stm.setString(1,jTextField10.getText());
            ResultSet r1 = stm.executeQuery();
            if(r1.next()==false)JOptionPane.showMessageDialog(null, "There are no person exist by your selection!","Error",JOptionPane.ERROR_MESSAGE);
            else{
                ResultSet r = stm.executeQuery();
                while(r.next() == true)
            {
                String id=r.getString("Name");
                    String asd=r.getString("agey");
                        String fath=r.getString("weight");
                            String moth=r.getString("bg");
                                String sex=r.getString("bp");
                                    String rel=r.getString("ttld");
                                        String ph=r.getString("Lddd");

            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(BM5.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data is not Exit By Your Selection");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
