
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BM6.java
 *
 * Created on Jul 9, 2011, 12:15:50 AM
 */

/**
 *
 * @author SHYFUL
 */
public class BM6 extends java.awt.Frame {
    private String id;
    private String asd;
    private String fath;
    private String moth;
    private String sex;
    private String rel;
    private String ph;
    private String ph1;
    private String ph2;
    private String ph3;
    private String ph4;
    private String ph5;

     private static class image {

        public image() {
        }
    }
   // private Component p2;
    //private String id;
    private String path;

    /** Creates new form BM6 */
    public BM6() {
        initComponents();setResizable(false);setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 320, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setText("Age:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 320, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel3.setText("Gender:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 320, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setText("Blood Group:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 320, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setText("Profession:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 320, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel7.setText("Present Address:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 320, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel8.setText("Permanent Address:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 320, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel18.setText("Phone No :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel14.setText("Last Donation Date :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 320, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 50, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 160, 30));

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, 30));

        jLabel9.setText("Enter id:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 80, 30));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 80, 30));

        jButton4.setText("Donation");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 90, 30));

        jButton5.setText("<Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 70, 30));

        jLabel6.setText("Day:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 40, -1));

        jLabel10.setText("Month :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 60, -1));

        jLabel11.setText("Year :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 70, -1));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 160, 190));

        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 170, 20));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 70, 40));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 170, 20));

        jLabel12.setFont(new java.awt.Font("Wide Latin", 0, 36));
        jLabel12.setText("Search Result");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 430, -1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 64, 140, 30));
        javax.swing.Timer t3 = new javax.swing.Timer(1000,new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Calendar cal = new GregorianCalendar();
                SimpleDateFormat h =new SimpleDateFormat("EEE, MMM dd, yyyy");
                String d3= h.format(cal.getTime());
                jLabel19.setText(d3);
            }
        });
        t3.start();

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        Connection con=null;
        PreparedStatement stm=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(BM5.class.getName()).log(Level.SEVERE, null, ex);
        }
        int i=0;
        try {
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bd","root","");
            stm = (PreparedStatement) con.prepareStatement("select * from `add` where `idn`=?");
            stm.setString(1,jTextField10.getText());
            ResultSet r1 = stm.executeQuery();
            if(r1.next()==false)JOptionPane.showMessageDialog(null, "There are no person exist by your selection!","Error",JOptionPane.ERROR_MESSAGE);
            else{
                ResultSet r = stm.executeQuery();
                while(r.next() == true) {
                     id=r.getString("Name");
                     asd=r.getString("agey");
                     fath=r.getString("gdr");
                     moth=r.getString("bg");
                     sex=r.getString("profession");
                     rel=r.getString("pre");
                     ph=r.getString("per");
                    ph1=r.getString("pn");
                     ph2=r.getString("Lddd");
                     ph3=r.getString("month");
                      ph4=r.getString("year");
                       ph5=r.getString("picture");
                       
                }
                jTextField1.setText(id);
                jTextField2.setText(asd);
                jTextField3.setText(fath);
                jTextField4.setText(moth);
                jTextField5.setText(sex);
                jTextArea1.setText(rel);
                jTextArea2.setText(ph);
                jTextField8.setText(ph1);
                jTextField9.setText(ph2);
                 jTextField6.setText(ph3);
                 jTextField7.setText(ph4);
                 //jButton6.setIcon((new ImageIcon(ph5)));

             File myFile=new File(ph5);
BufferedImage image = null;
                try {
                    image = ImageIO.read(myFile);
                } catch (IOException ex) {
                    Logger.getLogger(BM6.class.getName()).log(Level.SEVERE, null, ex);
                }
jButton6.setIcon(new ImageIcon(image.getScaledInstance(140,130,140)));


            }
        } catch (SQLException ex) {
            Logger.getLogger(BM5.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data is not exiSt By Your Selection");
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con = null;
        String url = "jdbc:mysql://localhost:3306/";
        String db = "bd";
        String driver = "com.mysql.jdbc.Driver";
        String user = "root";
        String pass = "";



        try {
            int x = JOptionPane.showConfirmDialog(null, "Are you sure to Confirm edit? All data will be replaced by present data !");
            if (x == 0) {
                try {

                    Class.forName(driver);
                    con = (Connection) DriverManager.getConnection(url + db, user, pass);
                    Statement st = (Statement) con.createStatement();
                    st.executeUpdate("UPDATE `bd`.`add` SET `idn` = '" + jTextField10.getText() + "', `Name` = '" + jTextField1.getText() + "', `agey` = '" + jTextField2.getText() + "', `gdr` = '" + jTextField3.getText() + "', `bg` = '" + jTextField4.getText() + "',  `profession` = '" + jTextField5.getText() + "',`pre` = '" + jTextArea1.getText() + "', `per` = '" + jTextArea2.getText() + "', `pn` = '" + jTextField8.getText() + "', `Lddd` = '" + jTextField9.getText() + "', `month` = '" + jTextField6.getText() + "', `year` = '" + jTextField7.getText() + "'  WHERE `idn` = '" + jTextField10.getText() + "' ");


                    JOptionPane.showMessageDialog(null, "Updated successfully completed");
                    con.close();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error in updating, please edit fields again !");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error");
        }



        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed


    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              String value = jTextField10.getText();
            Connection con = null;
		 String url = "jdbc:mysql://localhost:3306/";
		 String db = "bd";
		 String driver = "com.mysql.jdbc.Driver";
		 String user = "root";
		 String pass = "";
 try {
            int x = JOptionPane.showConfirmDialog(null, "Are you sure to Confirm Delete? All data will be replaced by present data !");
            if (x == 0) {
 try{
Class.forName(driver);
con =       (Connection) DriverManager.getConnection(url+db, user, pass);
PreparedStatement st=(PreparedStatement) con.prepareStatement("DELETE FROM `add` WHERE `idn` = ?");
 st.setString(1, value);
st.executeUpdate();
JOptionPane.showMessageDialog(null,"Data is successfully deleted database.");

con.close();
}


catch (Exception e)
{
 JOptionPane.showMessageDialog(null, "Error in deleting data!");

    //JOptionPane.showMessageDialog(null,"Data is successfully deleted from  database.");
}
}
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error");
        }
        dispose();
        new BM6().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     dispose();
        BM2 ok=new BM2();
ok.setVisible(true);    // TODO add your handling 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();
        BM7 ok=new BM7();
ok.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
String kycmd = new String(KeyEvent.getKeyText(evt.getKeyCode()));
        if (kycmd.equals("Enter")) {
        Connection con=null;
        PreparedStatement stm=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(BM5.class.getName()).log(Level.SEVERE, null, ex);
        }
        int i=0;
        try {
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bd","root","");
            stm = (PreparedStatement) con.prepareStatement("select * from `add` where `idn`=?");
            stm.setString(1,jTextField10.getText());
            ResultSet r1 = stm.executeQuery();
            if(r1.next()==false)JOptionPane.showMessageDialog(null, "There are no person exist by your selection!","Error",JOptionPane.ERROR_MESSAGE);
            else{
                ResultSet r = stm.executeQuery();
                while(r.next() == true) {
                     id=r.getString("Name");
                     asd=r.getString("agey");
                     fath=r.getString("gdr");
                     moth=r.getString("bg");
                     sex=r.getString("profession");
                     rel=r.getString("pre");
                     ph=r.getString("per");
                    ph1=r.getString("pn");
                     ph2=r.getString("Lddd");
                     ph3=r.getString("month");
                      ph4=r.getString("year");
                       ph5=r.getString("picture");

                }
                jTextField1.setText(id);
                jTextField2.setText(asd);
                jTextField3.setText(fath);
                jTextField4.setText(moth);
                jTextField5.setText(sex);
                jTextArea1.setText(rel);
                jTextArea2.setText(ph);
                jTextField8.setText(ph1);
                jTextField9.setText(ph2);
                 jTextField6.setText(ph3);
                 jTextField7.setText(ph4);
                 //jButton6.setIcon((new ImageIcon(ph5)));

             File myFile=new File(ph5);
BufferedImage image = null;
                try {
                    image = ImageIO.read(myFile);
                } catch (IOException ex) {
                    Logger.getLogger(BM6.class.getName()).log(Level.SEVERE, null, ex);
                }
jButton6.setIcon(new ImageIcon(image.getScaledInstance(140,130,140)));


            }
        } catch (SQLException ex) {
            Logger.getLogger(BM5.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data is not Exit By Your Selection");
        }



        } // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10KeyPressed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BM6().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
